### ISSUE TITLE
algorithm-reconize-vertebral-collumn Paper

### ISSUE THREAD

**Issue by YCTuTu** [G-Sponda/algorithm-reconize-vertebral-collumn#3]
Has your algorithm applied for the corresponding paper? If so,is it possible to release the paper for us to study?

**Comment by G-Sponda** [comment]
I have the Undergraduate thesis, but is in portuguese. If you don't have problem with that I can sent to you.

**Comment by YCTuTu** [comment]
Hello, thank you very much for your reply. I am a student in China and I am studying the direction of scoliosis. Thank you very much for sending me your graduation thesis. My email: TuYC163@163.com

**Comment by YCTuTu** [comment]
Thank you very much, I look forward to your reply, if the email can not be sent, you can upload to a platform, I will download

**Comment by G-Sponda** [comment]
I already sent to you in e-mail.
